### ISSUE TITLE
Review request list item limit value and behavior

### ISSUE THREAD

**Issue by johnastephenson** [BCDigLib/bostoncollege-branding#54]
Add value to plugin.init for request_list to limit maximum requested items to 20

AppConfig[:request_list] = {
:item_limit => 20,

When list is at capacity, the Request List menu tab changes color to pink. May want to revise this styling.

**Comment by johnastephenson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Define rules for requesting](https://trello.com/c/1wM1pQYX/89-define-rules-for-requesting)

**Comment by jessemartinez** [comment]
See recent commits here:
https://github.com/BCDigLib/request_list/commits/request_list_limit
