### ISSUE TITLE
HTML code appears in Identifier string

### ISSUE THREAD

**Issue by johnastephenson** [BCDigLib/bostoncollege-branding#57]
The Identifier string is displaying markup when titles feature italics (needs the html_safe fix).

Example record: http://helenus.bc.edu:8081/repositories/2/archival_objects/108900 

"Sub-Series D: <span class="italic title">The Tablet</span>, 1970-1974"

**Comment by johnastephenson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [HTML code appears in Identifier string](https://trello.com/c/XKb1Q7GF/169-html-code-appears-in-identifier-string)

**Comment by jessemartinez** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [HTML code appears in Identifier string (#57)](https://trello.com/c/XKb1Q7GF/169-html-code-appears-in-identifier-string-57)
