### ISSUE TITLE
Search Results: update icons

### ISSUE THREAD

**Issue by jessemartinez** [BCDigLib/bostoncollege-branding#7]
Tasks include: 

- Enlarge File, Person and Collection record type icons in search results,
- make colors accessible (not red/green),
- remove Subject icon.

**Comment by jessemartinez** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Search Results: Enlarge File, Person and Collection record type icons in search results & make colors accessible (not red/green). Remove Subject icon.](https://trello.com/c/s5EWRcL3/47-search-results-enlarge-file-person-and-collection-record-type-icons-in-search-results-make-colors-accessible-not-red-green-remov)

**Comment by johnastephenson** [comment]
Requires removal of entire badge (icon plus label) for Subject AND Classification records.
