### ISSUE TITLE
Advanced Search: Remove "Title" search limiter from advanced search

### ISSUE THREAD

**Issue by jessemartinez** [BCDigLib/bostoncollege-branding#8]

**Comment by jessemartinez** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Advanced Search: Remove "Title" search limiter from advanced search](https://trello.com/c/lk8gxm9b/22-advanced-search-remove-title-search-limiter-from-advanced-search)

**Comment by johnastephenson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Advanced Search: Remove "Title" search limiter from advanced search](https://trello.com/c/lk8gxm9b/22-advanced-search-remove-title-search-limiter-from-advanced-search)
